modLoader="javafml"
loaderVersion="[35,)"
license="GPLv3"

[[mods]]
modId="betternether"
version="${file.jarVersion}"
displayName="Better Nether Reforged"
displayURL="https://github.com/TomatoPuddin/BetterNether-Reforged"
logoFile= "icon.png"
credits="Paulevs for the original, Redd90 for the port"
authors="Paulevs (Fabric Original), SomeoneElse (Forge port), TomatoPuddin (Hotfix)"
description='''
'''

[[dependencies.betternether]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betternether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betternether]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[11.0.0.391,)"
    ordering="AFTER"
    side="BOTH"

